### ISSUE TITLE
[question] How can I make sure that when I am on a given node any value I cache belongs to that node?

### ISSUE THREAD

**Issue by Tochemey** [groupcache/groupcache-go#10]
Assuming we three nodes in the groupcache. 1,2 and 3. From the code when using the `Set` method https://github.com/groupcache/groupcache-go/blob/main/group.go#L138 a peer is picked for to own that key using some hash function.

That means that if I am on node 1 and want to cache a value in the group I may find the key of the value own by node 2. I need a correction if I am wrong. This is my question:

How can I make sure that when I am on a given node any value I cache belongs to that node?

cc: @thrawn01

**Comment by thrawn01** [comment]
Groupcache used Consistent Hashing to determine which nodes own a key. see https://www.toptal.com/big-data/consistent-hashing for an explanation of consistent Hashing

This is why groupcache must be informed of node changes in the cluster. If all nodes do not agree on who the owner is, then consistent hashing does not work as expected.
