### ISSUE TITLE
[Question] GetterFunc vs group.Get

### ISSUE THREAD

**Issue by Tochemey** [groupcache/groupcache-go#7]
@thrawn01 

Hello I would like to understand the importance of `GetterFunc` vs `group.Get`. Also does the developer needs to implement a local cache before implementing the `GetterFunc`. I am bit confused here.

In other cache libraries we just set the value and get the value but here to create a group in  the `deamon` we need that GetterFunc

It seems we may need some good documentation here :)

**Comment by thrawn01** [comment]
yes, this is a concept which needs to be better communicated. Groupcache is a `read-through cache`. 

### What is a Read Through Cache?
When an application requests data, the cache checks if it's already there. If it is, the cache returns the data immediately. If the data isn't in the cache, the cache retrieves it from the backend store, loads it into the cache, and returns it to the application

In groupcache, the `GetterFunc` is the function which retrieves the data from the backend, or thing you are caching. The value retrieved by `GetterFunc` is then cached locally. 

### Updating the README
I'll think up something to put into the readme, if you would be okay with reviewing it. I wonder if I could have chatGPT make us a diagram or animation which explains this system? (I suck a ChatGPT)

**Comment by Tochemey** [comment]
@thrawn01 I will be glad to review it.

**Comment by thrawn01** [comment]
@Tochemey I've created https://github.com/groupcache/groupcache-go/pull/8 please review!

**Comment by Tochemey** [comment]
@thrawn01 I will check it in a bit or morrow. Thanks
